# Generated by Django 6.0 on 2026-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allowedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='surname'),
        ),
    ]
