# Generated by Django 6.0 on 2026-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('doc_type', models.CharField(choices=[('matrix', 'Матрица'), ('nomenclature', 'Номенклатура'), ('price', 'Цены'), ('other', 'Другое')], default='other', max_length=100, verbose_name='Тип документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
