# Generated by Django 6.0 on 2025-12-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadedfile_description_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='doc_type',
            field=models.CharField(choices=[('matrix', 'Матрица'), ('nomenclature', 'Номенклатура'), ('price', 'Цены'), ('other', 'Другое')], default='other', max_length=100, verbose_name='Тип документа'),
        ),
    ]
