# Generated by Django 6.0 on 2026-02-08 14:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=core.models.file_upload_path, verbose_name='Файл'),
        ),
    ]
